apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-webserver
  namespace: my-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: golang-webserver
  template:
    metadata:
      labels:
        app: golang-webserver
    spec:
      initContainers:
      - name: init-sleep
        image: busybox
        command: ["sleep", "30"]
      containers:
      - name: golang-webserver
        image: $MY_NEW_IMAGE
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "echo 'Prestop Hook executed'"]
---
apiVersion: v1
kind: Service
metadata:
  name: golang-webserver-service
  namespace: my-namespace
spec:
  selector:
    app: golang-webserver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
